library(DESeq2)
colData <- read.csv("C:/Users/Lab Members/PycharmProjects/research/miRNA/nuc_man_info.csv",header = T, sep = ',')
colData$BUID <- as.factor(colData$BUID)
colData$subjectID <- as.factor(colData$subjectID)
colData$miRNA_batch <- as.factor(colData$miRNA_batch)
colData$cogdx <- as.factor(colData$cogdx)
colData$age_death <- as.factor(colData$age_death)
colData$msex <- as.factor(colData$msex)
colData$RIN <- as.factor(colData$RIN)
colData$sampleID <- as.factor(colData$sampleID)
colData$brain_region <- as.factor(colData$brain_region)
cts <- as.matrix(read.csv("C:/Users/Lab Members/PycharmProjects/research/miRNA/nuc_man_data.csv",header = T, sep=','))
ddsHTSeq <- DESeqDataSetFromMatrix(countData = cts, colData = colData, design = ~ RIN + age_death)
#ddsHTSeq <- DESeq(ddsHTSeq)
ddsHTSeq <- estimateSizeFactors(ddsHTSeq)
ddsHTSeq <- estimateDispersions(ddsHTSeq)
ddsHTSeq <- nbinomWaldTest(ddsHTSeq, maxit=10000)
write.csv(as.data.frame(counts(ddsHTSeq, normalize=T)), "man_nuc_normalized_counts.csv")
#res <- results(ddsHTSeq, contrast=c("cogdx", alpha=0.05)
